Replace 'tput' call with inlined ANSI for better performance, patch samples

diff --git a/tools/sh/chruby/chruby-init b/tools/sh/chruby/chruby-init
--- a/tools/sh/chruby/chruby-init
+++ b/tools/sh/chruby/chruby-init
@@ -2,11 +2,11 @@
 
 case "$1" in
   core)
-    dir="$(realpath "$0")"; dir="${dir%/*}"
+    dir=$(realpath "$0"); dir=${dir%/*}
     cat "$dir/chruby.sh"
     ;;
   auto)
-    dir="$(realpath "$0")"; dir="${dir%/*}"
+    dir=$(realpath "$0"); dir=${dir%/*}
 cat << HEREDOC
 if ! command -v chruby >/dev/null; then
   source "$dir/chruby.sh"
@@ -16,9 +16,9 @@ HEREDOC
     cat "$dir/auto.sh"
     ;;
   *)
-    echo "echo 'chruby-init failed!'" 2>&1
-    echo "echo 'chruby-init should be called with either 'core' or 'auto', like:'" 2>&1
-    echo "echo 'eval \"\$(chruby-init core)\"'" 2>&1
+    echo "echo 'chruby-init failed!'" >&2
+    echo "echo 'chruby-init should be called with either 'auto' or 'manual', like:'" >&2
+    echo "echo 'eval \"\$(chruby-init core)\"'" >&2
     exit 1
     ;;
 esac
